UploadPic/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'UploadPic.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r"^pic/", include("pic.urls", namespace="pic")),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
  urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})    
  )

pic/urls.py
from django.conf.urls import patterns, url, static, include
from django.contrib import admin
from django.views.generic import TemplateView

from pic import views

urlpatterns = patterns('',
  url(r'^uploadfile/$', views.uploadpic, name='uploadpic'),
  url(r'^listfiles/$', views.displaypic, name='displaypic'),
  url(r'^afterupload/$', TemplateView.as_view(template_name='pic/afterupload.html'), name='afterupload')
)

pic/models.py
import datetime

from django.db import models


# Create your models here.
class UploadPic(models.Model):
  file = models.FileField(upload_to="uploads")

pic/forms.py
from django import forms
from pic.models import UploadPic

class UploadPicForm(forms.ModelForm):
  class Meta:
    model = UploadPic
    

pic/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from .forms import UploadPicForm
from pic.models import UploadPic

# Create your views here.
def uploadpic(request):
  if request.method == 'POST':
    form = UploadPicForm(request.POST, request.FILES)
    if form.is_valid():
      form.save()
      return render(request, 'pic/afterupload.html')
  else:
    form = UploadPicForm()
  return render(request, 'pic/upload.html', {'form':form})


def displaypic(request):
  imgNames = [p.file.name for p in UploadPic.objects.all()]
  return render(request, 'pic/listfiles.html', {'names': imgNames})

pic/templates/pic/afterupload.html
{% extends 'pic/base.html' %}
{% load staticfiles %}


<link rel="stylesheet" type="text/css" href="{% static 'pic/style.css' %}" />


{% block Main %}
<section class="desc">
   <p>You've just uploaded a picture!</p>
</section>

<section class="desc" id="links">
   <a href="{% url 'pic:uploadpic' %}">* upload new picture *</a>
   </br>
   <a href="{% url 'pic:displaypic' %}">* view gallery *</a>
</section>
{% endblock %}

pic/templates/pic/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
   <head>
      <title>Django Photo App</title>
      <link href='http://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
      <link rel="stylesheet" type="text/css" href="{% static 'pic/style.css' %}" />
      <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
   <head>
   
   <body>
      
      <header id="title">
         <p>UPLOAD YOUR PICTURES</p>
      </header>
      
      {% block Main %}
      {% endblock %}
      
      
      <footer id="myname">
         <div id="centered">
         <p> © Sangeeta Jadoonanan</p>
         </div>
      </footer>
   </body>
</html>

pic/templates/pic/listfiles.html
{% extends 'pic/base.html' %}
{% load staticfiles %}


<link rel="stylesheet" type="text/css" href="{% static 'pic/style.css' %}" />


{% block Main %}
<section class="desc">
<p>Picture Gallery</p>
</section>


{% for name in names %}
<img id='pics' src="{{ MEDIA_URL }}{{ name }}" scale="0.7"/>
{% endfor %}


<section class="desc" id="links">
<p>Start over!</p>
<a href="{% url 'pic:uploadpic' %}">Upload a new picture!</a>
</section>
{% endblock %}

pic/templates/pic/upload.html
{% extends 'pic/base.html' %}
{% load staticfiles %}


<link rel="stylesheet" type="text/css" href="{% static 'pic/style.css' %}" />


{% block Main %}
<section class="desc">
   <p>
      A simple Django app.
      Just upload your pics and see them on your screen!
   </p>
</section>

<section class="forms">
   <form id="form" action="." method="post" enctype="multipart/form-data">
   
      {% csrf_token %}
      {{ form }}
      <input class="buttons" type="submit" name="upload" value="upload">
   </form>
</section>
{% endblock %}